# Netlify configuration file

[build]
  command = "npm run build"
  publish = ".next"

# Next.js specific headers
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Secret scanning configuration
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_GTM_ID"
